from __future__ import annotations


class ModelConfig:
    def __init__(
        self,
        d_model: int = 512,
        n_outer_latents: int = 128,
        n_outer_cycles: int = 3,
        n_outer_heads: int = 8,
        n_inner_cycles: int = 6,
        n_inner_heads: int = 8,
        n_broadcast_cycles: int = 0,
        n_latent_heads: int = 8,
        d_ff: int = 2048,
        local_conv_kernel: int = 7,
        dropout: float = 0.0,
        routing_k: int = 32,
        n_center_latents: int = 4,
        max_seq_len: int = 2048,
        use_grad_ckpt: bool = False,
        proj_chunk: int = 0,
        causal: bool = True,
        harp_max_heads: int = 8,
        harp_tl_scale: float = 1.0,
        use_internalization: bool = False,
        internalization_steps: int = 3,
        return_internalization_loss: bool = False,
        use_adaptive_halting: bool = False,
        adaptive_epsilon: float = 1e-6,
        max_adaptive_steps: int = 10,
        use_jfb: bool = True,
        use_qk_norm: bool = True,
        use_rezero: bool = True,
        rezero_init: float = 1e-4,
        use_compile: bool = False,
        compile_mode: str = "default",
        cycle_drop: bool = False,
        min_inner_cycles: int = 2,
        use_compaction: bool = True,
        d_compact: int | None = None,
        compaction_loss_weight: float = 0.1,
        vocab_size: int = 0,
        use_ib: bool = False,
        macro_jump: int = 4,
        btt_max_levels: int = 40,
        merger_path: str = "merger.pt",
        use_q_cache: bool = True,
        mask_cache_mb: float = 256.0,
    ):
        self.d_model = d_model
        self.n_outer_latents = n_outer_latents
        self.n_outer_cycles = n_outer_cycles
        self.n_outer_heads = n_outer_heads
        self.n_inner_cycles = n_inner_cycles
        self.n_inner_heads = n_inner_heads
        self.n_broadcast_cycles = n_broadcast_cycles
        self.n_latent_heads = n_latent_heads
        self.d_ff = d_ff
        self.local_conv_kernel = local_conv_kernel
        self.dropout = dropout
        self.routing_k = routing_k
        self.n_center_latents = n_center_latents
        self.max_seq_len = max_seq_len
        self.use_grad_ckpt = use_grad_ckpt
        self.proj_chunk = proj_chunk
        self.causal = causal
        self.harp_max_heads = harp_max_heads
        self.harp_tl_scale = harp_tl_scale
        self.use_internalization = use_internalization
        self.internalization_steps = internalization_steps
        self.return_internalization_loss = return_internalization_loss
        self.use_adaptive_halting = use_adaptive_halting
        self.adaptive_epsilon = adaptive_epsilon
        self.max_adaptive_steps = max_adaptive_steps
        self.use_jfb = use_jfb
        self.use_qk_norm = use_qk_norm
        self.use_rezero = use_rezero
        self.rezero_init = rezero_init
        self.use_compile = use_compile
        self.compile_mode = compile_mode
        self.cycle_drop = cycle_drop
        self.min_inner_cycles = max(1, min_inner_cycles)
        self.use_compaction = use_compaction
        self.d_compact = d_compact
        self.compaction_loss_weight = compaction_loss_weight
        self.vocab_size = vocab_size
        self.use_ib = use_ib and (vocab_size > 0)
        self.macro_jump = macro_jump
        self.btt_max_levels = btt_max_levels
        self.merger_path = merger_path
        self.use_q_cache = use_q_cache
        self.mask_cache_mb = mask_cache_mb